### ISSUE TITLE
Await Issue in Core for re-integrate steps, chart in object_attributes

### ISSUE THREAD

**Issue by gaudes** [gaudes/iobroker-object-helper#13]
See https://github.com/ioBroker/adapter-core/issues/283

Wait for depending issue, see also comments in object_attributes.

**Comment by AlCalzone** [comment]
@types/iobroker changes are on the way: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49618

**Comment by gaudes** [comment]
Fixed in PR #19
