### ISSUE TITLE
validateObjectTree broken with array.some()

### ISSUE THREAD

**Issue by gaudes** [gaudes/iobroker-object-helper#38]
iobIDPath.forEach(iobIDName =>{
	//if (iobObjects.filter(item => item.id === `${iobIDBasePath}${iobIDName}`).length > 1){
	if (iobObjects.some(item => item.id === `${iobIDBasePath}${iobIDName}`)){

commented line is correct, length must be more than 1. array.some finds only first occurance.

**Comment by AlCalzone** [comment]
Huh? What if you only have one object you want to save?

**Comment by gaudes** [comment]
This part is for detecting duplicates :) Next line is "throw ..."

Original intend of this part:
One element is ok, but two elements with same id is a duplicate.

Bug now:
One element ? Error saying duplicate
